name: scrape-hyperliquid

permissions:
  contents: write

on:
  schedule:
    - cron: '*/5 * * * *'    # 매 5분마다 실행
  workflow_dispatch:        # 수동 실행도 가능

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Ubuntu 24.04 에서 지원되는 버전

      - name: Install dependencies
        run: pip install selenium webdriver-manager pandas

      - name: Run scraper
        run: python scrape_leaderboard.py

      - name: Commit & Push CSV
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add top30_wallets.csv
          git diff --quiet && echo "No changes" || git commit -m "chore: update top30_wallets.csv"
          git push
