name: scrape-hyperliquid

on:
  schedule:
    - cron:  '0 * * * *'    # every hour
  workflow_dispatch:      # also allow manual run

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install selenium webdriver-manager pandas

      - name: Run scraper
        run: python scrape_top30.py

      - name: Commit & Push CSV
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add top30_wallets.csv
          git diff --quiet && echo "No changes" || git commit -m "chore: update top30_wallets.csv"
          git push
