# .github/workflows/scrape.yml
name: scrape-hyperliquid

on:
  schedule:
    - cron: '*/5 * * * *'    # 매 5분마다 실행
  workflow_dispatch:        # 수동 트리거도 가능

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager pandas

      - name: Run scraper (and capture errors)
        continue-on-error: true
        run: |
          set -eux
          python scrape_leaderboard.py 2>&1 | tee scrape.log
          cat scrape.log

      - name: Commit & Push updated CSV (if changed)
        if: ${{ success() || failure() }}
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add top30_wallets.csv
          git diff --quiet || (git commit -m "chore: update top30_wallets.csv" && git push)
