name: scrape-hyperliquid

# 반드시 쓰기 권한을 줘야 GITHUB_TOKEN 으로 커밋/푸시가 가능합니다
permissions:
  contents: write

on:
  schedule:
    # 매 5분마다 실행
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install selenium webdriver-manager pandas

      - name: Run scraper
        run: python scrape_leaderboard.py | tee scrape.log

      - name: Debug scrape log
        if: failure()
        run: cat scrape.log

      - name: Commit & Push CSV
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add top30_wallets.csv
          git diff --quiet && echo "No changes" || git commit -m "chore: update top30_wallets.csv"
          git push
